[package]
name = "nsloth"
version = "0.1.0"
edition = "2021"
authors = ["MyselfLeo"]
description = "A weird, slow and a bit moldy interpreted programming language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.3", features = ["derive"] }
regex = "1.5.6"
text_io = "0.1.10"
sloth_derive = { path = "sloth_derive" }